export const  countries = [
  {"CountryName": "Afghanistan", "CountryID": "AF"},
  {"CountryName": "Åland Islands", "CountryID": "AX"},
  {"CountryName": "Albania", "CountryID": "AL"},
  {"CountryName": "Algeria", "CountryID": "DZ"},
  {"CountryName": "American Samoa", "CountryID": "AS"},
  {"CountryName": "AndorrA", "CountryID": "AD"},
  {"CountryName": "Angola", "CountryID": "AO"},
  {"CountryName": "Anguilla", "CountryID": "AI"},
  {"CountryName": "Antarctica", "CountryID": "AQ"},
  {"CountryName": "Antigua and Barbuda", "CountryID": "AG"},
  {"CountryName": "Argentina", "CountryID": "AR"},
  {"CountryName": "Armenia", "CountryID": "AM"},
  {"CountryName": "Aruba", "CountryID": "AW"},
  {"CountryName": "Australia", "CountryID": "AU"},
  {"CountryName": "Austria", "CountryID": "AT"},
  {"CountryName": "Azerbaijan", "CountryID": "AZ"},
  {"CountryName": "Bahamas", "CountryID": "BS"},
  {"CountryName": "Bahrain", "CountryID": "BH"},
  {"CountryName": "Bangladesh", "CountryID": "BD"},
  {"CountryName": "Barbados", "CountryID": "BB"},
  {"CountryName": "Belarus", "CountryID": "BY"},
  {"CountryName": "Belgium", "CountryID": "BE"},
  {"CountryName": "Belize", "CountryID": "BZ"},
  {"CountryName": "Benin", "CountryID": "BJ"},
  {"CountryName": "Bermuda", "CountryID": "BM"},
  {"CountryName": "Bhutan", "CountryID": "BT"},
  {"CountryName": "Bolivia", "CountryID": "BO"},
  {"CountryName": "Bosnia and Herzegovina", "CountryID": "BA"},
  {"CountryName": "Botswana", "CountryID": "BW"},
  {"CountryName": "Bouvet Island", "CountryID": "BV"},
  {"CountryName": "Brazil", "CountryID": "BR"},
  {"CountryName": "British Indian Ocean Territory", "CountryID": "IO"},
  {"CountryName": "Brunei Darussalam", "CountryID": "BN"},
  {"CountryName": "Bulgaria", "CountryID": "BG"},
  {"CountryName": "Burkina Faso", "CountryID": "BF"},
  {"CountryName": "Burundi", "CountryID": "BI"},
  {"CountryName": "Cambodia", "CountryID": "KH"},
  {"CountryName": "Cameroon", "CountryID": "CM"},
  {"CountryName": "Canada", "CountryID": "CA"},
  {"CountryName": "Cape Verde", "CountryID": "CV"},
  {"CountryName": "Cayman Islands", "CountryID": "KY"},
  {"CountryName": "Central African Republic", "CountryID": "CF"},
  {"CountryName": "Chad", "CountryID": "TD"},
  {"CountryName": "Chile", "CountryID": "CL"},
  {"CountryName": "China", "CountryID": "CN"},
  {"CountryName": "Christmas Island", "CountryID": "CX"},
  {"CountryName": "Cocos (Keeling) Islands", "CountryID": "CC"},
  {"CountryName": "Colombia", "CountryID": "CO"},
  {"CountryName": "Comoros", "CountryID": "KM"},
  {"CountryName": "Congo", "CountryID": "CG"},
  {"CountryName": "Congo, The Democratic Republic of the", "CountryID": "CD"},
  {"CountryName": "Cook Islands", "CountryID": "CK"},
  {"CountryName": "Costa Rica", "CountryID": "CR"},
  {"CountryName": "Cote D Ivoire", "CountryID": "CI"},
  {"CountryName": "Croatia", "CountryID": "HR"},
  {"CountryName": "Cuba", "CountryID": "CU"},
  {"CountryName": "Cyprus", "CountryID": "CY"},
  {"CountryName": "Czech Republic", "CountryID": "CZ"},
  {"CountryName": "Denmark", "CountryID": "DK"},
  {"CountryName": "Djibouti", "CountryID": "DJ"},
  {"CountryName": "Dominica", "CountryID": "DM"},
  {"CountryName": "Dominican Republic", "CountryID": "DO"},
  {"CountryName": "Ecuador", "CountryID": "EC"},
  {"CountryName": "Egypt", "CountryID": "EG"},
  {"CountryName": "El Salvador", "CountryID": "SV"},
  {"CountryName": "Equatorial Guinea", "CountryID": "GQ"},
  {"CountryName": "Eritrea", "CountryID": "ER"},
  {"CountryName": "Estonia", "CountryID": "EE"},
  {"CountryName": "Ethiopia", "CountryID": "ET"},
  {"CountryName": "Falkland Islands (Malvinas)", "CountryID": "FK"},
  {"CountryName": "Faroe Islands", "CountryID": "FO"},
  {"CountryName": "Fiji", "CountryID": "FJ"},
  {"CountryName": "Finland", "CountryID": "FI"},
  {"CountryName": "France", "CountryID": "FR"},
  {"CountryName": "French Guiana", "CountryID": "GF"},
  {"CountryName": "French Polynesia", "CountryID": "PF"},
  {"CountryName": "French Southern Territories", "CountryID": "TF"},
  {"CountryName": "Gabon", "CountryID": "GA"},
  {"CountryName": "Gambia", "CountryID": "GM"},
  {"CountryName": "Georgia", "CountryID": "GE"},
  {"CountryName": "Germany", "CountryID": "DE"},
  {"CountryName": "Ghana", "CountryID": "GH"},
  {"CountryName": "Gibraltar", "CountryID": "GI"},
  {"CountryName": "Greece", "CountryID": "GR"},
  {"CountryName": "Greenland", "CountryID": "GL"},
  {"CountryName": "Grenada", "CountryID": "GD"},
  {"CountryName": "Guadeloupe", "CountryID": "GP"},
  {"CountryName": "Guam", "CountryID": "GU"},
  {"CountryName": "Guatemala", "CountryID": "GT"},
  {"CountryName": "Guernsey", "CountryID": "GG"},
  {"CountryName": "Guinea", "CountryID": "GN"},
  {"CountryName": "Guinea-Bissau", "CountryID": "GW"},
  {"CountryName": "Guyana", "CountryID": "GY"},
  {"CountryName": "Haiti", "CountryID": "HT"},
  {"CountryName": "Heard Island and Mcdonald Islands", "CountryID": "HM"},
  {"CountryName": "Holy See (Vatican City State)", "CountryID": "VA"},
  {"CountryName": "Honduras", "CountryID": "HN"},
  {"CountryName": "Hong Kong", "CountryID": "HK"},
  {"CountryName": "Hungary", "CountryID": "HU"},
  {"CountryName": "Iceland", "CountryID": "IS"},
  {"CountryName": "India", "CountryID": "IN"},
  {"CountryName": "Indonesia", "CountryID": "ID"},
  {"CountryName": "Iran, Islamic Republic Of", "CountryID": "IR"},
  {"CountryName": "Iraq", "CountryID": "IQ"},
  {"CountryName": "Ireland", "CountryID": "IE"},
  {"CountryName": "Isle of Man", "CountryID": "IM"},
  {"CountryName": "Israel", "CountryID": "IL"},
  {"CountryName": "Italy", "CountryID": "IT"},
  {"CountryName": "Jamaica", "CountryID": "JM"},
  {"CountryName": "Japan", "CountryID": "JP"},
  {"CountryName": "Jersey", "CountryID": "JE"},
  {"CountryName": "Jordan", "CountryID": "JO"},
  {"CountryName": "Kazakhstan", "CountryID": "KZ"},
  {"CountryName": "Kenya", "CountryID": "KE"},
  {"CountryName": "Kiribati", "CountryID": "KI"},
  {"CountryName": "Korea, Democratic People S Republic of", "CountryID": "KP"},
  {"CountryName": "Korea, Republic of", "CountryID": "KR"},
  {"CountryName": "Kuwait", "CountryID": "KW"},
  {"CountryName": "Kyrgyzstan", "CountryID": "KG"},
  {"CountryName": "Laos", "CountryID": "LA"},
  {"CountryName": "Latvia", "CountryID": "LV"},
  {"CountryName": "Lebanon", "CountryID": "LB"},
  {"CountryName": "Lesotho", "CountryID": "LS"},
  {"CountryName": "Liberia", "CountryID": "LR"},
  {"CountryName": "Libyan Arab Jamahiriya", "CountryID": "LY"},
  {"CountryName": "Liechtenstein", "CountryID": "LI"},
  {"CountryName": "Lithuania", "CountryID": "LT"},
  {"CountryName": "Luxembourg", "CountryID": "LU"},
  {"CountryName": "Macao", "CountryID": "MO"},
  {"CountryName": "Macedonia", "CountryID": "MK"},
  {"CountryName": "Madagascar", "CountryID": "MG"},
  {"CountryName": "Malawi", "CountryID": "MW"},
  {"CountryName": "Malaysia", "CountryID": "MY"},
  {"CountryName": "Maldives", "CountryID": "MV"},
  {"CountryName": "Mali", "CountryID": "ML"},
  {"CountryName": "Malta", "CountryID": "MT"},
  {"CountryName": "Marshall Islands", "CountryID": "MH"},
  {"CountryName": "Martinique", "CountryID": "MQ"},
  {"CountryName": "Mauritania", "CountryID": "MR"},
  {"CountryName": "Mauritius", "CountryID": "MU"},
  {"CountryName": "Mayotte", "CountryID": "YT"},
  {"CountryName": "Mexico", "CountryID": "MX"},
  {"CountryName": "Micronesia, Federated States of", "CountryID": "FM"},
  {"CountryName": "Moldova, Republic of", "CountryID": "MD"},
  {"CountryName": "Monaco", "CountryID": "MC"},
  {"CountryName": "Mongolia", "CountryID": "MN"},
  {"CountryName": "Montserrat", "CountryID": "MS"},
  {"CountryName": "Morocco", "CountryID": "MA"},
  {"CountryName": "Mozambique", "CountryID": "MZ"},
  {"CountryName": "Myanmar", "CountryID": "MM"},
  {"CountryName": "Namibia", "CountryID": "NA"},
  {"CountryName": "Nauru", "CountryID": "NR"},
  {"CountryName": "Nepal", "CountryID": "NP"},
  {"CountryName": "Netherlands", "CountryID": "NL"},
  {"CountryName": "Netherlands Antilles", "CountryID": "AN"},
  {"CountryName": "New Caledonia", "CountryID": "NC"},
  {"CountryName": "New Zealand", "CountryID": "NZ"},
  {"CountryName": "Nicaragua", "CountryID": "NI"},
  {"CountryName": "Niger", "CountryID": "NE"},
  {"CountryName": "Nigeria", "CountryID": "NG"},
  {"CountryName": "Niue", "CountryID": "NU"},
  {"CountryName": "Norfolk Island", "CountryID": "NF"},
  {"CountryName": "Northern Mariana Islands", "CountryID": "MP"},
  {"CountryName": "Norway", "CountryID": "NO"},
  {"CountryName": "Oman", "CountryID": "OM"},
  {"CountryName": "Pakistan", "CountryID": "PK"},
  {"CountryName": "Palau", "CountryID": "PW"},
  {"CountryName": "Palestinian Territory, Occupied", "CountryID": "PS"},
  {"CountryName": "Panama", "CountryID": "PA"},
  {"CountryName": "Papua New Guinea", "CountryID": "PG"},
  {"CountryName": "Paraguay", "CountryID": "PY"},
  {"CountryName": "Peru", "CountryID": "PE"},
  {"CountryName": "Philippines", "CountryID": "PH"},
  {"CountryName": "Pitcairn", "CountryID": "PN"},
  {"CountryName": "Poland", "CountryID": "PL"},
  {"CountryName": "Portugal", "CountryID": "PT"},
  {"CountryName": "Puerto Rico", "CountryID": "PR"},
  {"CountryName": "Qatar", "CountryID": "QA"},
  {"CountryName": "Reunion", "CountryID": "RE"},
  {"CountryName": "Romania", "CountryID": "RO"},
  {"CountryName": "Russian Federation", "CountryID": "RU"},
  {"CountryName": "RWANDA", "CountryID": "RW"},
  {"CountryName": "Saint Helena", "CountryID": "SH"},
  {"CountryName": "Saint Kitts and Nevis", "CountryID": "KN"},
  {"CountryName": "Saint Lucia", "CountryID": "LC"},
  {"CountryName": "Saint Pierre and Miquelon", "CountryID": "PM"},
  {"CountryName": "Saint Vincent and the Grenadines", "CountryID": "VC"},
  {"CountryName": "Samoa", "CountryID": "WS"},
  {"CountryName": "San Marino", "CountryID": "SM"},
  {"CountryName": "Sao Tome and Principe", "CountryID": "ST"},
  {"CountryName": "Saudi Arabia", "CountryID": "SA"},
  {"CountryName": "Senegal", "CountryID": "SN"},
  {"CountryName": "Serbia and Montenegro", "CountryID": "CS"},
  {"CountryName": "Seychelles", "CountryID": "SC"},
  {"CountryName": "Sierra Leone", "CountryID": "SL"},
  {"CountryName": "Singapore", "CountryID": "SG"},
  {"CountryName": "Slovakia", "CountryID": "SK"},
  {"CountryName": "Slovenia", "CountryID": "SI"},
  {"CountryName": "Solomon Islands", "CountryID": "SB"},
  {"CountryName": "Somalia", "CountryID": "SO"},
  {"CountryName": "South Africa", "CountryID": "ZA"},
  {"CountryName": "South Georgia and the South Sandwich Islands", "CountryID": "GS"},
  {"CountryName": "Spain", "CountryID": "ES"},
  {"CountryName": "Sri Lanka", "CountryID": "LK"},
  {"CountryName": "Sudan", "CountryID": "SD"},
  {"CountryName": "SuriCountryName", "CountryID": "SR"},
  {"CountryName": "Svalbard and Jan Mayen", "CountryID": "SJ"},
  {"CountryName": "Swaziland", "CountryID": "SZ"},
  {"CountryName": "Sweden", "CountryID": "SE"},
  {"CountryName": "Switzerland", "CountryID": "CH"},
  {"CountryName": "Syrian Arab Republic", "CountryID": "SY"},
  {"CountryName": "Taiwan, Province of China", "CountryID": "TW"},
  {"CountryName": "Tajikistan", "CountryID": "TJ"},
  {"CountryName": "Tanzania, United Republic of", "CountryID": "TZ"},
  {"CountryName": "Thailand", "CountryID": "TH"},
  {"CountryName": "Timor-Leste", "CountryID": "TL"},
  {"CountryName": "Togo", "CountryID": "TG"},
  {"CountryName": "Tokelau", "CountryID": "TK"},
  {"CountryName": "Tonga", "CountryID": "TO"},
  {"CountryName": "Trinidad and Tobago", "CountryID": "TT"},
  {"CountryName": "Tunisia", "CountryID": "TN"},
  {"CountryName": "Turkey", "CountryID": "TR"},
  {"CountryName": "Turkmenistan", "CountryID": "TM"},
  {"CountryName": "Turks and Caicos Islands", "CountryID": "TC"},
  {"CountryName": "Tuvalu", "CountryID": "TV"},
  {"CountryName": "Uganda", "CountryID": "UG"},
  {"CountryName": "Ukraine", "CountryID": "UA"},
  {"CountryName": "United Arab Emirates", "CountryID": "AE"},
  {"CountryName": "United Kingdom", "CountryID": "GB"},
  {"CountryName": "United States", "CountryID": "US"},
  {"CountryName": "United States Minor Outlying Islands", "CountryID": "UM"},
  {"CountryName": "Uruguay", "CountryID": "UY"},
  {"CountryName": "Uzbekistan", "CountryID": "UZ"},
  {"CountryName": "Vanuatu", "CountryID": "VU"},
  {"CountryName": "Venezuela", "CountryID": "VE"},
  {"CountryName": "Viet Nam", "CountryID": "VN"},
  {"CountryName": "Virgin Islands, British", "CountryID": "VG"},
  {"CountryName": "Virgin Islands, U.S.", "CountryID": "VI"},
  {"CountryName": "Wallis and Futuna", "CountryID": "WF"},
  {"CountryName": "Western Sahara", "CountryID": "EH"},
  {"CountryName": "Yemen", "CountryID": "YE"},
  {"CountryName": "Zambia", "CountryID": "ZM"},
  {"CountryName": "Zimbabwe", "CountryID": "ZW"}
  ];